### PR TITLE
Use de same extension from resourcePath

### PR DESCRIPTION
**Pull request by jhuss**
related with issue #8:
- this allow use the loader with other lang such as TypeScript

### CODE REVIEW

**Review by zmagyar — APPROVED** [review]

**Comment by Lendingstandard-Bill** [comment]
Good day, working on a Extjs 4.2 project - would you think this (if configured correctly) would be able to support legacy Extjs app?

**Comment by zmagyar** [comment]
Hi, we have never tried it with legacy versions, sorry.

**Comment by steveetm** [comment]
@Lendingstandard-Bill It depends what do you really want to include in bundle.
This loader can bundle both your codebase and extjs sdk, that way you don't even have to include ext-all.js, only required ext sources are included. But this mode is really not tested, this plugin uses `extjs-parser` which supposed to parse extjs source code to create required class name and override mapping to filesystem path, which is most likely cannot work with extjs@4 oob.

But if bundling _only_ your codebase and you will include ext-all.js manually, you can definitely use this _if_ you don't have a lot of ext anti-pattern usages.
```
module.exports = {
  module: {
    rules: [
      {
        test: /\.js/,
        use: [
            {
                loader: 'extjs-loader',
                debug: true,
                nameSpace: 'MyAppNamespace',
                paths: {
                    'Deft': false,
                    'Ext': false,
                    'MyAppNamespace': 'yourSourceCodeDirectory'
                }
            } ]
      }
    ]
  }
}
```

You entry point e.g. `index.js` with this content:
```
 Ext.application({
        name: 'MyAppNamespace',

        extend: 'MyAppNamespace.Application',

        requires: []
});
```
and in `yourSourceCodeDirectory/Applications.js`:
```
Ext.define('MyAppNamespace.Application', {
    name: 'MyAppNamespace',
    extend: 'Ext.app.Application',
    [...]
```

It should work, just don't forget to add `ext-all.js` _before_ the generated bundle.

**Comment by Lendingstandard-Bill** [comment]
Good day all,
Thanks for the help.. I’ll try it tonight and see what happen.  Bill

**Pull request merged**
